# Generated by Django 5.1.2 on 2024-11-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0058_alter_chatmessage_options_otpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
