# Generated by Django 5.1.2 on 2024-11-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0060_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date']},
        ),
    ]
