# Generated by Django 5.1.3 on 2024-11-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0065_company_alter_order_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehousedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=30)),
                ('length', models.CharField(max_length=30)),
                ('breadth', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('packed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_service', models.CharField(max_length=30)),
                ('tracking_id', models.IntegerField()),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('shipped_date', models.DateField(auto_now_add=True)),
                ('boxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.warehousedata')),
            ],
        ),
    ]
