# Generated by Django 5.0.6 on 2024-11-14 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0066_warehousedata_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='parcel_service',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='warehousedata',
            name='shipped_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='warehousedata',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehousedata',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='warehousedata',
            name='tracking_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
