# Generated by Django 5.0.6 on 2024-11-14 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0068_warehousedata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedata',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_orders', to='beposoft_app.order'),
        ),
    ]
