# Generated by Django 5.0.6 on 2024-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0070_alter_warehousedata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedata',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
