# Generated by Django 5.0.6 on 2024-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0071_alter_warehousedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='height',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='shipped_date',
            field=models.DateField(),
        ),
    ]
