# Generated by Django 5.1.3 on 2024-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0073_grvmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grvmodel',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grvmodel',
            name='remark',
            field=models.CharField(choices=[('return', 'Return'), ('refund', 'Refund')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grvmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, null=True),
        ),
    ]
