# Generated by Django 5.1.3 on 2024-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0074_alter_grvmodel_note_alter_grvmodel_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grvmodel',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
