# Generated by Django 5.1.3 on 2024-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0077_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
