# Generated by Django 5.1.3 on 2024-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0078_order_date_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='grvmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grvmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
