# Generated by Django 5.1.3 on 2024-11-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0082_expensemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
    ]
