# Generated by Django 5.1.3 on 2024-11-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0083_rename_transcation_id_expensemodel_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='payment_mode',
            new_name='purpose_of_payment',
        ),
    ]
