# Generated by Django 5.1.3 on 2024-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0084_rename_payment_mode_expensemodel_purpose_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
