# Generated by Django 5.1.3 on 2024-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0085_expensemodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='added_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
