# Generated by Django 5.1.3 on 2024-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0086_expensemodel_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
