# Generated by Django 5.1.3 on 2024-12-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0087_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grvmodel',
            name='date',
        ),
    ]
