# Generated by Django 5.1.3 on 2024-12-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0089_alter_order_time_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Invoice Created', 'Invoice Created'), ('Invoice Approved', 'Invoice Approved'), ('Waiting For Confirmation', 'Waiting For Confirmation'), ('Packing under progress', 'Packing under progress'), ('Packing', 'Packing'), ('Ready to ship', 'Ready to ship'), ('To Print', 'To Print'), ('Invoice Rejectd', 'Invoice Rejectd'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Return', 'Return')], default='Pending', max_length=100),
        ),
    ]
